version: "3.8"

services:
  frontend:
    build: ./client/bulgarian-waters
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - redis
